console.log("Hello world");
var peg=require("pegjs");
var peg = require("pegjs");
var fs= require("fs");
var filename='grammer.pegjs';
var grammerDemo=fs.readFileSync(filename,'utf-8');
var parser = peg.generate(grammerDemo);
var input='4410038386';
var output =parser.parse(input);
console.log(output);